modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "wrench_wrapper"
version = "${version}"
displayName = "Wrench Wrapper"
logoFile = "assets/wrench_wrapper/icon.png"
authors = "Ennui Langeweile, The Quilt Project"
description = """
A handy wrapper for your Quilt Config!
"""
