modLoader = "javafml"
loaderVersion = "*"
license = "MIT"

[[mods]]
modId = "wrench_wrapper"
version = "${version}"
displayName = "Wrench Wrapper"
logoFile = "icon.png"
authors = "Ennui Langeweile"
description = """
A handy wrapper for your Quilt Config!
"""
